config/routes.rb
Fisherific::Application.routes.draw do
  
  root :to => "static_pages#home"
  match "/projects" => "static_pages#projects"
  match "/about" => "static_pages#about"

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def projects
  end

  def about
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title)
    base_title = "fisherific"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
  def menu_select(title)
    if title == controller.action_name
      "class='selected'"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
	
	<div id="footer_inner">

		<div class="hr"><hr /></div>
	
		<p>&copy; Copyright 2012 James Fisher</p>

	</div>

</div>

app/views/layouts/_header.html.erb
<div id="header">
	
	<div id="header_inner">
		
		<div id="title">
			<h1><%= link_to "[fisherific]", root_path %></h1>
		</div>

		<div id="nav">
			<ul class="nav">
				
				<li <%= menu_select('home') %> ><%= link_to "Home", root_path, :class => 'nav_item' %></li>
				<li <%= menu_select('projects') %> ><%= link_to "Projects", projects_path, :class => 'nav_item' %></li>
				<li <%= menu_select('about') %> ><%= link_to "About", about_path, :class => 'nav_item' %></li>
				
			</ul>
		</div>
		
					<div style="display: block; clear: both;"></div>
	
	</div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

	<link href='http://fonts.googleapis.com/css?family=Cabin|Crete+Round|Pontano+Sans|Merriweather' rel='stylesheet' type='text/css'>
	<link href="/img/favicon.png" rel="shortcut icon" type="image/x-icon" />
	<meta name="viewport" content="width=device-width; initial-scale=1.0">
	
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-32606824-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
	
</head>
<body>
<div id="wrapper">
	
	<%= render 'layouts/header' %>

	<div id="main">
		
		<div id="main_inner">

				<%= yield %>
			
		</div>
		
	</div>
	
	<%= render 'layouts/footer' %>

</div>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "about")%>

<div id="title_container">
	<h2 class='main_title'>About me</h2>
</div>
						
<div class="hr_title"><hr /></div>
		
<div class="content_item">

	<div class='item_body'>
			
		<div class='col1'>
				
			<p>Hi. I'm James Fisher, a Toronto based analyst / web developer / general hacker.

				I like to build things with modern, open source technologies.  I've got experience with the following:
				</p>
				
			<ul>
				<li>HTML, CSS</li>
				<li>Javascript, jQuery</li>
				<li>Perl</li>
				<li>Ruby/Rails</li>
				<li>Lots of SQL (MySQL, MSSQL)</li>
				<li>Processing</li>
			</ul>

			<p>I tweet very infrequently at <a href='http://twitter.com/fisherific'>@fisherific </a></p>
		
			<p>Best way to get is touch is via email: <a href="mailto:james@fisherific.com">james@fisherific.com</a></p>
						
		</div>
		
		<div class="col2">
			
			<img src="/assets/jaf5.jpg" id="profile">
				
		</div>
			
	<div style="display: block; clear: both;"></div>
	
	</div>

</div>
			

app/views/static_pages/home.html.erb
<% provide(:title, "home")%>

<div id="title_container_home">
	<h2 class="home_text">Hi.  I'm James Fisher.</h2>
</div>
			
<h2 class="home_subtitle1">I like to use <span class="home_bold1"> open source technology </span> to solve problems.</h2>
	
<h2 class="home_subtitle2">I live and work in Toronto, Canada.</h2>
	
<br>
	
<div class='col1 home'>
		
	<h3>Check out some of my projects:</h3>

	<div class="hr_title"><hr /></div>
			
	<%= link_to image_tag('map_med.png'), projects_path %>
				
</div>

<div class="col2 home">

	<h3>Learn a bit more about me:</h3>

	<div class="hr_title"><hr /></div>
			
	<%= link_to image_tag('jaf2_med.jpg'), about_path %>

</div>

<div style="display: block; clear: both;"></div>
	

<script>
	$(".home_text").fitText(0.89);
	
	if ($(window).width() < 500 ){
		
		
		$(".home_subtitle1").fitText(1.6);
		$(".home_subtitle2").fitText(1.6);

		
	}else{
		
		$(".home_subtitle1").fitText(2.45);
		$(".home_subtitle2").fitText(2.45);
		
	}
	
	
	$(window).resize(function(){
		
		if ($(window).width() < 500 ){
			
			
			$(".home_subtitle1").fitText(1.5);
			$(".home_subtitle2").fitText(1.5);

			
		}else{
			
			$(".home_subtitle1").fitText(2.45);
			$(".home_subtitle2").fitText(2.45);
			
		}
		

		
	})
	

</script>

app/views/static_pages/projects.html.erb
<% provide(:title, "projects")%>

<div id="title_container">
	<h2 class='main_title'>Projects</h2>
</div>		
<div class="hr_title"><hr /></div>

<div class="content_item">
						


	<div class='item_body'>
				
		<div class='col1'>

			<a href="http://www.flickr.com/photos/indexity/6686861143/" title="TTC Speeds 2 by indexity, on Flickr"><img src="http://farm8.staticflickr.com/7011/6686861143_b0d6623f69_b.jpg" alt="TTC Speeds 2"></a>
			<a href="http://www.flickr.com/photos/indexity/6722822427/" title="TTC Speeds - Low Sample Rate by indexity, on Flickr"><img src="http://farm8.staticflickr.com/7169/6722822427_8dddc8e7d3_b.jpg" alt="TTC Speeds - Low Sample Rate"></a>

		</div>
					
		<div class="col2">
			
				<h3 class='content_title'>Toronto Transit Speeds</h3>

			<p>A data exploration project visualizing the speed of every surface route of 
				the TTC. All the TTC buses and streetcars traced for 6 hours the morning of 
				January 6th, 2012.  Average speed is indicated by colour, red being the slowest, 
				followed by orange, yellow, green and blue.
			</p>	
							
			<p>Check out the feature in <a href="http://torontoist.com/2012/01/colour-coding-your-commute/">Torontoist</a>, 
				as well as some mentions in the
				<a href="http://www.thestar.com/news/transportation/article/1121806--ttc-routes-during-rush-hour-watch-them-all-at-once">Toronto Star</a> and
				<a href="http://www.globaltoronto.com/video/a+birdseye+view+of+the+ttc/video.html?v=2190485386#segments/video">Global News</a>.
			</p>
									
			<p>Thanks to Open Data Toronto.  Built using Processing, QGIS, and some Photoshop for touchups.</p>
			
		</div>
					
		<div style="display: block; clear: both;"></div>
	
	</div>

</div>

<div class="hr"><hr /></div>

<div class="content_item">

	<div class='item_body'>
			
		<div class='col1'>

			<a href="http://indexity.net/vis/hw"><img src='/assets/data_explorer.png'></a>

		</div>
	
		<div class="col2">
			
				<h3 class='content_title'>Hollywood Data Explorer</h3>

			<p>An entry into the <a href='http://www.informationisbeautifulawards.com/2012/03/hall-of-fame-hollywood-challenge-winners/'>Information is Beautiful Hollywood Challenge</a>.
			
				This highly interactive web application is designed to explore some of 
				the metrics coming out of Hollywood. The tool covers over 500 films from 
				the past 5 years.
			</p>	
				
			<p>The data explorer specifically takes a neutral stance, 
				and allows the users to draw their own conclusions. 
				 There are literally thousands of possible combinations.
			</p>	
			
		
			<p>Built with lots of <a href='http://d3js.org'>d3</a> and jQuery.  
				Placed 2nd place in the interactive category.
			
			</p>
		</div>
				
		<div style="display: block; clear: both;"></div>

	</div>

</div>

<div class="hr"><hr /></div>

<div class='content_item'>
			
	<div class='col1'>
		<img src='/assets/fisherific.png'>
	</div>
	<div class="col2">
		
		<h3 class='content_title'>fisherific.com</h3>

		<p>The site you're looking at right now.  An effort to share some of my personal 
			projects with anyone who is interested.  Still a work in progress.
					
		</p>	
						
		<p>Built on Ruby on Rails (overkill at the moment, but more is coming). 
			 Responsive design works on a huge range of screen sizes and devices.
		</p>	
					
	</div>
	
	<div style="display: block; clear: both;"></div>

</div>


	




				